language: cpp

dist: trusty

before_install:
- sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
- sudo add-apt-repository ppa:beineri/opt-qt561-trusty -y
- sudo apt-get update -qq

install:
- sudo apt-get install -y --force-yes -qq g++-5 gcc-5; export CXX="g++-5" CC="gcc-5"; $CXX --version
- sudo apt-get install -y --force-yes -qq qt56base qt56declarative; source /opt/qt56/bin/qt56-env.sh

script:
  - mkdir build
  - cd build
  - qmake ..
  - make -j4 CC=gcc-5 CXX=g++-5 LINK=g++-5

notifications:
  irc:
    channels:
      - "irc.choopa.net#firebird-emu"
    on_success: change
    on_failure: always
    skip_join: true
